// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dvqkkqvjsqjnvwwvxenh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cWtrcXZqc3FqbnZ3d3Z4ZW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODYzNDQsImV4cCI6MjA3MDM2MjM0NH0.y5jMtIVTgA2p_ywvch73Ni2oYYKu5D_jkaHp0o_aFM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);